<a href="https://colab.research.google.com/github/John-Kyalo/Data-Analysis-with-Python/blob/main/DA_analysis_practices.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Honing Data Analysis skills with Python by focusing on a movie dataset**

Jamesbond dataset from kaggle

**Objectives:**


1.  Is there any relationship between the Rotten Tomatoes ratings and those  
    from IMDb?
2.  Are there any insights to be gleaned from analyzing the lengths of the
    movies?
3.  Is there a relationship between the number of enemies James Bond has killed
    and the user ratings of the movie in which they were killed?

**LOADING PACKAGES AND DATASET**

In [67]:
#Import libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import warnings
warnings.filterwarnings('ignore')

In [68]:
#Load dataset
df = pd.read_csv('/content/jamesbond.csv')
df.head()

,Year,Movie,Bond,Director,Composer,Writer,Cinematographer,Depicted_Film_Loc,Shooting_Loc,Bond_Car_MFG,...,Film_Length,Avg_User_IMDB,Avg_User_Rtn_Tom,Conquests,Martinis,BJB,Kills_Bond,Kills_Others,Top_100,Video_Game
0,1962,Dr. No,Sean Connery,Terence Young,Monty Norman,"Richard Maibaum, Johanna Harwood & Berkely Mather",Ted Moore,"Great Britain, Jamaic","England, Jamaica",Sunbeam,...,110,7.3,7.7,3,2,1,4,8,0,0
1,1963,From Russia with Love,Sean Connery,Terence Young,John Barry,Richard Maibaum & Johanna Harwood,Ted Moore,"United Kingdom, Great Britain, Turkey, Croatia...","England, Scotland, Italy, Switzerland, Turkey",Bently,...,115,7.5,8.0,4,0,0,11,16,0,1
2,1964,Goldfinger,Sean Connery,Guy Hamilton,John Barry,Richard Maibaum & Paul Dehn,Ted Moore,"United States, Great Britain, Switzerland","England, Switzerland, United States",Aston Martin,...,110,7.8,8.4,2,1,2,9,68,1,1
3,1965,Thunderball,Sean Connery,Terence Young,John Barry,Richard Maibaum & John Hopkins,Ted Moore,"France, Great Britain, Bahamas, United States","England, France, Bahamas, United States",Aston Martin,...,130,7.0,6.8,3,0,0,20,90,1,0
4,1967,You Only Live Twice,Sean Connery,Lewis Gilbert,John Barry,Roald Dahl,Freddie Young,"United States, Russia, Kazakhstan, Norway, Japan","Japan, Spain, Norway",Toyota,...,117,6.9,6.3,3,1,0,21,175,1,0

In [69]:
df.shape #explore dataset

(24, 27)

In [54]:
list(df.columns)

['Year',
 'Movie',
 'Bond',
 'Director',
 'Composer',
 'Writer',
 'Cinematographer',
 'Depicted_Film_Loc',
 'Shooting_Loc',
 'Bond_Car_MFG',
 'Bond_Girl_Nat',
 'US_Gross',
 'US_Adj',
 'World_Gross',
 'World_Adj',
 'Budget',
 'Budget_Adj',
 'Film_Length',
 'Avg_User_IMDB',
 'Avg_User_Rtn_Tom',
 'Conquests',
 'Martinis',
 'BJB',
 'Kills_Bond',
 'Kills_Others',
 'Top_100',
 'Video_Game']

**Cleaning Dataset**

In [70]:
#Have column names in lowercase
new_column_names = {
       "Year": "release_date",
       "Movie": "movie_title",
       "Bond": "bond_actor",
       "Bond_Car_MFG": "car_manufacturer",
       "US_Gross": "income_usa",
       "World_Gross": "income_world",
       "Budget": "movie_budget",
       "Film_Length": "film_length",
       "Avg_User_IMDB": "imdb",
       "Avg_User_Rtn_Tom": "rotten_tomatoes",
       "Martinis": "martinis_consumed",
       "Kills_Bond": "bond_kills",
}

df.rename(columns=new_column_names, inplace=True)

In [71]:
df.columns

Index(['release_date', 'movie_title', 'bond_actor', 'Director', 'Composer',
       'Writer', 'Cinematographer', 'Depicted_Film_Loc', 'Shooting_Loc',
       'car_manufacturer', 'Bond_Girl_Nat', 'income_usa', 'US_Adj',
       'income_world', 'World_Adj', 'movie_budget', 'Budget_Adj',
       'film_length', 'imdb', 'rotten_tomatoes', 'Conquests',
       'martinis_consumed', 'BJB', 'bond_kills', 'Kills_Others', 'Top_100',
       'Video_Game'],
      dtype='object')

In [72]:
to_drop = ['Director', 'Composer', 'Writer', 'Cinematographer', 'Depicted_Film_Loc', 'Shooting_Loc', 'Bond_Girl_Nat',
             'US_Adj', 'World_Adj', 'Budget_Adj', 'Conquests', 'BJB', 'Kills_Others', 'Top_100', 'Video_Game']
df.drop(to_drop, axis=1, inplace=True)

In [73]:
#Dealing with missing data
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 24 entries, 0 to 23
Data columns (total 12 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   release_date       24 non-null     int64
 1   movie_title        24 non-null     object
 2   bond_actor         24 non-null     object
 3   car_manufacturer   24 non-null     object
 4   income_usa         24 non-null     int64
 5   income_world       24 non-null     int64
 6   movie_budget       24 non-null     int64
 7   film_length        24 non-null     int64
 8   imdb               24 non-null     float64
 9   rotten_tomatoes    24 non-null     float64
 10  martinis_consumed  24 non-null     int64
 11  bond_kills         24 non-null     int64
dtypes: float64(2), int64(7), object(3)
memory usage: 2.4+ KB

In [74]:
df.isna().sum()

release_date         0
movie_title          0
bond_actor           0
car_manufacturer     0
income_usa           0
income_world         0
movie_budget         0
film_length          0
imdb                 0
rotten_tomatoes      0
martinis_consumed    0
bond_kills           0
dtype: int64

In [75]:
df[['income_usa', 'income_world', 'movie_budget']].head()

   income_usa  income_world  movie_budget
0    16067035      59567035          1000
1    24800000      78900000          2000
2    51100000     124900000          3000
3    63600000     141200000          9000
4    43100000     111600000          9500

In [76]:
df.describe()

,release_date,income_usa,income_world,movie_budget,film_length,imdb,rotten_tomatoes,martinis_consumed,bond_kills
count,24.000000,2.400000e+01,2.400000e+01,24.000000,24.000000,24.000000,24.000000,24.000000,24.000000
mean,1984.291667,8.576758e+07,2.882462e+08,62091.666667,126.833333,6.858333,6.479167,1.083333,17.000000
std,16.617118,7.116355e+07,2.657106e+08,75828.564749,10.961064,0.517449,0.967282,1.316011,11.348243
min,1962.000000,1.606704e+07,5.956704e+07,1000.000000,106.000000,6.000000,4.700000,0.000000,1.000000
25%,1970.500000,4.117500e+07,1.226750e+08,7800.000000,119.750000,6.500000,5.975000,0.000000,8.750000
50%,1982.000000,5.299250e+07,1.864500e+08,29000.000000,127.500000,6.800000,6.300000,1.000000,14.000000
75%,1997.500000,1.257109e+08,3.577551e+08,104000.000000,131.500000,7.125000,6.825000,1.000000,26.250000
max,2015.000000,3.043603e+08,1.108561e+09,245000.000000,148.000000,7.900000,8.400000,6.000000,47.000000

In [77]:
#Check for duplicate data
df.duplicated().sum()

0

In [78]:
df.to_csv('/content/jamesbond_cleaned.csv', index = False)